# Generated by Django 6.0.2 on 2026-03-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analytics', '0002_alter_data_age_alter_data_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='salary',
            field=models.PositiveIntegerField(),
        ),
    ]
